from PermSpec_Base import PermutationSpec, permutation_spec_from_axes_to_perm

def sd2_permutation_spec() -> PermutationSpec:
    conv = lambda name, p_in, p_out: {  # pylint: disable=unnecessary-lambda-assignment
        f"{name}.weight": (
            p_out,
            p_in,
        ),
        f"{name}.bias": (p_out,),
    }
    norm = lambda name, p: {f"{name}.weight": (p,), f"{name}.bias": (p,)}  # pylint: disable=unnecessary-lambda-assignment
    dense = (
        lambda name, p_in, p_out, bias=True: {  # pylint: disable=unnecessary-lambda-assignment
            f"{name}.weight": (p_out, p_in),
            f"{name}.bias": (p_out,),
        }
        if bias
        else {f"{name}.weight": (p_out, p_in)}
    )
    # Layer name is somehow changed!
    dense2 = (
        lambda name, p_in, p_out, bias=True: {  # pylint: disable=unnecessary-lambda-assignment
            f"{name}_weight": (p_out, p_in),
            f"{name}_bias": (p_out,),
        }
        if bias
        else {f"{name}_weight": (p_out, p_in)}
    )
    skip = lambda name, p_in, p_out: {  # pylint: disable=unnecessary-lambda-assignment
        f"{name}": (
            p_out,
            p_in,
            None,
            None,
        )
    }

    # Unet Res blocks
    easyblock = lambda name, p_in, p_out: {  # pylint: disable=unnecessary-lambda-assignment
        **norm(f"{name}.in_layers.0", p_in),
        **conv(f"{name}.in_layers.2", p_in, f"P_{name}_inner"),
        **dense(
            f"{name}.emb_layers.1", f"P_{name}_inner2", f"P_{name}_inner3", bias=True
        ),
        **norm(f"{name}.out_layers.0", f"P_{name}_inner4"),
        **conv(f"{name}.out_layers.3", f"P_{name}_inner4", p_out),
    }

    # Text Encoder blocks
    easyblock2 = lambda name, p: {
        **norm(f"{name}.norm1", p),
        **conv(f"{name}.conv1", p, f"P_{name}_inner"),
        **norm(f"{name}.norm2", f"P_{name}_inner"),
        **conv(f"{name}.conv2", f"P_{name}_inner", p),
    }

    # This is for blocks that use a residual connection, but change the number of channels via a Conv.
    shortcutblock = lambda name, p_in, p_out: {
        **norm(f"{name}.norm1", p_in),
        **conv(f"{name}.conv1", p_in, f"P_{name}_inner"),
        **norm(f"{name}.norm2", f"P_{name}_inner"),
        **conv(f"{name}.conv2", f"P_{name}_inner", p_out),
        **conv(f"{name}.nin_shortcut", p_in, p_out),
        **norm(f"{name}.nin_shortcut", p_out),
    }

    return permutation_spec_from_axes_to_perm(
        {
            # Skipped Layers
            **skip("betas", None, None),
            **skip("alphas_cumprod", None, None),
            **skip("alphas_cumprod_prev", None, None),
            **skip("sqrt_alphas_cumprod", None, None),
            **skip("sqrt_one_minus_alphas_cumprod", None, None),
            **skip("sqrt_recip_alphas_cumprod", None, None),
            **skip("sqrt_recipm1_alphas_cumprod", None, None),
            **skip("posterior_variance", None, None),
            **skip("posterior_log_variance_clipped", None, None),
            **skip("posterior_mean_coef1", None, None),
            **skip("posterior_mean_coef2", None, None),
            **skip("log_one_minus_alphas_cumprod", None, None),
            **skip("model_ema.decay", None, None),
            **skip("model_ema.num_updates", None, None),

            #initial 
            **dense("model.diffusion_model.time_embed.0", None, "P_bg0", bias=True),
            **dense("model.diffusion_model.time_embed.2","P_bg0", "P_bg1", bias=True),
            **conv("model.diffusion_model.input_blocks.0.0", "P_bg2", "P_bg3"),
            
            #input blocks    
            **easyblock("model.diffusion_model.input_blocks.1.0","P_bg4", "P_bg5"),     
            **norm("model.diffusion_model.input_blocks.1.1.norm", "P_bg6"),
            **conv("model.diffusion_model.input_blocks.1.1.proj_in", "P_bg6", "P_bg7"),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_q", "P_bg8", "P_bg9", bias=False),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_k", "P_bg8", "P_bg9", bias=False),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_v", "P_bg8", "P_bg9", bias=False),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0", "P_bg8", "P_bg9", bias=True),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj", "P_bg10", "P_bg11", bias=True),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2", "P_bg12", "P_bg13", bias=True),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_q", "P_bg14", "P_bg15", bias=False),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k", "P_bg16", "P_bg17", bias=False),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v", "P_bg16", "P_bg17", bias=False),
            **dense("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0", "P_bg18", "P_bg19", bias=True),
            **norm("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1", "P_bg19" ),
            **norm("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2", "P_bg19"),
            **norm("model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3", "P_bg19"),
            **conv("model.diffusion_model.input_blocks.1.1.proj_out", "P_bg19", "P_bg20"),

            **easyblock("model.diffusion_model.input_blocks.2.0", "P_bg21","P_bg22"),
            **norm("model.diffusion_model.input_blocks.2.1.norm", "P_bg23"),  
            **conv("model.diffusion_model.input_blocks.2.1.proj_in", "P_bg23", "P_bg24"),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_q", "P_bg25", "P_bg26", bias=False),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_k", "P_bg25", "P_bg26", bias=False),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_v", "P_bg25", "P_bg26", bias=False),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0", "P_bg25","P_bg26", bias=True),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj", "P_bg27","P_bg28", bias=True),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2", "P_bg29","P_bg30", bias=True),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_q", "P_bg31", "P_bg32", bias=False),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k", "P_bg33", "P_bg34", bias=False),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v", "P_bg33", "P_bg34", bias=False),
            **dense("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0", "P_bg35","P_bg36", bias=True),
            **norm("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1", "P_bg36"),
            **norm("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2", "P_bg36"),
            **norm("model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3", "P_bg36"),
            **conv("model.diffusion_model.input_blocks.2.1.proj_out", "P_bg36", "P_bg37"),   

            **conv("model.diffusion_model.input_blocks.3.0.op", "P_bg38", "P_bg39"),
            **easyblock("model.diffusion_model.input_blocks.4.0", "P_bg40","P_bg41"),
            **conv("model.diffusion_model.input_blocks.4.0.skip_connection", "P_bg42","P_bg43"),
            **norm("model.diffusion_model.input_blocks.4.1.norm", "P_bg44"),
            **conv("model.diffusion_model.input_blocks.4.1.proj_in", "P_bg44", "P_bg45"),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q", "P_bg46", "P_bg47", bias=False),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_k", "P_bg46", "P_bg47", bias=False),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_v", "P_bg46", "P_bg47", bias=False),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0", "P_bg46","P_bg47", bias=True),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj", "P_bg48","P_bg49", bias=True),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2", "P_bg50","P_bg51", bias=True),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_q", "P_bg52", "P_bg53", bias=False),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k", "P_bg54", "P_bg55", bias=False),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v", "P_bg54", "P_bg55", bias=False),
            **dense("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0", "P_bg56","P_bg57", bias=True),
            **norm("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1", "P_bg57"),
            **norm("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2", "P_bg57"),
            **norm("model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3", "P_bg57"),
            **conv("model.diffusion_model.input_blocks.4.1.proj_out", "P_bg57", "P_bg58"),   

            **easyblock("model.diffusion_model.input_blocks.5.0", "P_bg59", "P_bg60"),
            **norm("model.diffusion_model.input_blocks.5.1.norm", "P_bg61"),
            **conv("model.diffusion_model.input_blocks.5.1.proj_in", "P_bg61", "P_bg62"),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_q", "P_bg63", "P_bg64", bias=False),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_k", "P_bg63", "P_bg64", bias=False),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_v", "P_bg63", "P_bg64", bias=False),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0", "P_bg63","P_bg64", bias=True),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj", "P_bg65","P_bg66", bias=True),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2", "P_bg67","P_bg68", bias=True),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_q", "P_bg69", "P_bg70", bias=False),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k", "P_bg71", "P_bg72", bias=False),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v", "P_bg71", "P_bg72", bias=False),
            **dense("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0", "P_bg73","P_bg74", bias=True),
            **norm("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1", "P_bg74"),
            **norm("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2", "P_bg74"),
            **norm("model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3", "P_bg74"),
            **conv("model.diffusion_model.input_blocks.5.1.proj_out", "P_bg74", "P_bg75"),

            **conv("model.diffusion_model.input_blocks.6.0.op", "P_bg76", "P_bg77"),
            **easyblock("model.diffusion_model.input_blocks.7.0", "P_bg78","P_bg79"),
            **conv("model.diffusion_model.input_blocks.7.0.skip_connection", "P_bg80","P_bg81"),
            **norm("model.diffusion_model.input_blocks.7.1.norm", "P_bg82"),
            **conv("model.diffusion_model.input_blocks.7.1.proj_in", "P_bg82", "P_bg83"),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_q", "P_bg84", "P_bg85", bias=False),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_k", "P_bg84", "P_bg85", bias=False),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_v", "P_bg84", "P_bg85", bias=False),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0", "P_bg84","P_bg85", bias=True),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj", "P_bg86","P_bg87", bias=True),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2", "P_bg88","P_bg89", bias=True),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_q", "P_bg90", "P_bg91", bias=False),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k", "P_bg92", "P_bg93", bias=False),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v", "P_bg92", "P_bg93", bias=False),
            **dense("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0", "P_bg94","P_bg95", bias=True),
            **norm("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1", "P_bg95"),
            **norm("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2", "P_bg95"),
            **norm("model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3", "P_bg95"),
            **conv("model.diffusion_model.input_blocks.7.1.proj_out", "P_bg95", "P_bg96"),
            
            **easyblock("model.diffusion_model.input_blocks.8.0", "P_bg97","P_bg98"),
            **norm("model.diffusion_model.input_blocks.8.1.norm", "P_bg99"),
            **conv("model.diffusion_model.input_blocks.8.1.proj_in", "P_bg99", "P_bg100"),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_q", "P_bg101", "P_bg102", bias=False),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_k", "P_bg101", "P_bg102", bias=False),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_v", "P_bg101", "P_bg102", bias=False),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0", "P_bg101","P_bg102", bias=True),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj", "P_bg103","P_bg104", bias=True),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2", "P_bg105","P_bg106", bias=True),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_q", "P_bg107", "P_bg108", bias=False),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k", "P_bg109", "P_bg110", bias=False),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v", "P_bg109", "P_bg110", bias=False),
            **dense("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0", "P_bg111","P_bg112", bias=True),
            **norm("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1", "P_bg112"),
            **norm("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2", "P_bg112"),
            **norm("model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3", "P_bg112"),
            **conv("model.diffusion_model.input_blocks.8.1.proj_out", "P_bg112", "P_bg113"),
            
            **conv("model.diffusion_model.input_blocks.9.0.op", "P_bg114", "P_bg115"),
            **easyblock("model.diffusion_model.input_blocks.10.0", "P_bg115", "P_bg116"),
            **easyblock("model.diffusion_model.input_blocks.11.0", "P_bg116", "P_bg117"),
            
            #middle blocks
            **easyblock("model.diffusion_model.middle_block.0", "P_bg117", "P_bg118"),
            **norm("model.diffusion_model.middle_block.1.norm", "P_bg119"),
            **conv("model.diffusion_model.middle_block.1.proj_in", "P_bg119", "P_bg120"),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_q", "P_bg121", "P_bg122", bias=False),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_k", "P_bg121", "P_bg122", bias=False),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_v", "P_bg121", "P_bg122", bias=False),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0", "P_bg121","P_bg122", bias=True),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj", "P_bg123","P_bg124", bias=True),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2", "P_bg125","P_bg126", bias=True),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_q", "P_bg127", "P_bg128", bias=False),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k", "P_bg129", "P_bg130", bias=False),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v", "P_bg129", "P_bg130", bias=False),
            **dense("model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0", "P_bg131","P_bg132", bias=True),
            **norm("model.diffusion_model.middle_block.1.transformer_blocks.0.norm1", "P_bg132"),
            **norm("model.diffusion_model.middle_block.1.transformer_blocks.0.norm2", "P_bg132"),
            **norm("model.diffusion_model.middle_block.1.transformer_blocks.0.norm3", "P_bg132"),
            **conv("model.diffusion_model.middle_block.1.proj_out", "P_bg132", "P_bg133"),
            
            **easyblock("model.diffusion_model.middle_block.2", "P_bg134", "P_bg135"),
            
            #output blocks
            **easyblock("model.diffusion_model.output_blocks.0.0", "P_bg136", "P_bg137"),
            **conv("model.diffusion_model.output_blocks.0.0.skip_connection","P_bg138","P_bg139"),

            **easyblock("model.diffusion_model.output_blocks.1.0", "P_bg140","P_bg141"),  
            **conv("model.diffusion_model.output_blocks.1.0.skip_connection","P_bg142","P_bg143"),

            
            **easyblock("model.diffusion_model.output_blocks.2.0", "P_bg144","P_bg145"),
            **conv("model.diffusion_model.output_blocks.2.0.skip_connection","P_bg146","P_bg147"),
            **conv("model.diffusion_model.output_blocks.2.1.conv", "P_bg148", "P_bg149"),
            
            **easyblock("model.diffusion_model.output_blocks.3.0", "P_bg150","P_bg151"),
            **conv("model.diffusion_model.output_blocks.3.0.skip_connection","P_bg152","P_bg153"),
            **norm("model.diffusion_model.output_blocks.3.1.norm", "P_bg154"),
            **conv("model.diffusion_model.output_blocks.3.1.proj_in", "P_bg154", "P_bg155"),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q", "P_bg156", "P_bg157", bias=False),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k", "P_bg156", "P_bg157", bias=False),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v", "P_bg156", "P_bg157", bias=False),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0", "P_bg156","P_bg157", bias=True),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj", "P_bg158","P_bg159", bias=True),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2", "P_bg160","P_bg161", bias=True),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q", "P_bg162", "P_bg163", bias=False),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k", "P_bg164", "P_bg165", bias=False),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v", "P_bg164", "P_bg165", bias=False),
            **dense("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0", "P_bg166","P_bg167", bias=True),
            **norm("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1", "P_bg167"),
            **norm("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2", "P_bg167"),
            **norm("model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3", "P_bg167"),
            **conv("model.diffusion_model.output_blocks.3.1.proj_out", "P_bg167", "P_bg168"),

            **easyblock("model.diffusion_model.output_blocks.4.0", "P_bg169", "P_bg170"),
            **conv("model.diffusion_model.output_blocks.4.0.skip_connection","P_bg171","P_bg172"),
            **norm("model.diffusion_model.output_blocks.4.1.norm", "P_bg173"),
            **conv("model.diffusion_model.output_blocks.4.1.proj_in", "P_bg173", "P_bg174"),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q", "P_bg175", "P_bg176", bias=False),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k", "P_bg175", "P_bg176", bias=False),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v", "P_bg175", "P_bg176", bias=False),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0", "P_bg175","P_bg176", bias=True),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj", "P_bg177","P_bg178", bias=True),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2", "P_bg179","P_bg180", bias=True),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q", "P_bg181", "P_bg182", bias=False),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k", "P_bg183", "P_bg184", bias=False),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v", "P_bg183", "P_bg184", bias=False),
            **dense("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0", "P_bg185","P_bg186", bias=True),
            **norm("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1", "P_bg186"),
            **norm("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2", "P_bg186"),
            **norm("model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3", "P_bg186"),
            **conv("model.diffusion_model.output_blocks.4.1.proj_out", "P_bg186", "P_bg187"),
            
            **easyblock("model.diffusion_model.output_blocks.5.0", "P_bg188", "P_bg189"),
            **conv("model.diffusion_model.output_blocks.5.0.skip_connection","P_bg190","P_bg191"),
            **norm("model.diffusion_model.output_blocks.5.1.norm", "P_bg192"),
            **conv("model.diffusion_model.output_blocks.5.1.proj_in", "P_bg192", "P_bg193"),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q", "P_bg194", "P_bg195", bias=False),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k", "P_bg194", "P_bg195", bias=False),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v", "P_bg194", "P_bg195", bias=False),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0", "P_bg194","P_bg195", bias=True),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj", "P_bg196","P_bg197", bias=True),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2", "P_bg198","P_bg199", bias=True),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q", "P_bg200", "P_bg201", bias=False),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k", "P_bg202", "P_bg203", bias=False),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v", "P_bg202", "P_bg203", bias=False),
            **dense("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0", "P_bg204","P_bg205", bias=True),
            **norm("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1", "P_bg205"),
            **norm("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2", "P_bg205"),
            **norm("model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3", "P_bg205"),
            **conv("model.diffusion_model.output_blocks.5.1.proj_out", "P_bg205", "P_bg206"),
            **conv("model.diffusion_model.output_blocks.5.2.conv", "P_bg206", "P_bg207"),
            
            **easyblock("model.diffusion_model.output_blocks.6.0", "P_bg208","P_bg209"),
            **conv("model.diffusion_model.output_blocks.6.0.skip_connection","P_bg210","P_bg211"),
            **norm("model.diffusion_model.output_blocks.6.1.norm", "P_bg212"),
            **conv("model.diffusion_model.output_blocks.6.1.proj_in", "P_bg212", "P_bg213"),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_q", "P_bg214", "P_bg215", bias=False),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_k", "P_bg214", "P_bg215", bias=False),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_v", "P_bg214", "P_bg215", bias=False),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0", "P_bg214","P_bg215", bias=True),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj", "P_bg216","P_bg217", bias=True),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2", "P_bg218","P_bg219", bias=True),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_q", "P_bg220", "P_bg221", bias=False),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_k", "P_bg222", "P_bg223", bias=False),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_v", "P_bg222", "P_bg223", bias=False),
            **dense("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0", "P_bg224","P_bg225", bias=True),
            **norm("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1", "P_bg225"),
            **norm("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2", "P_bg225"),
            **norm("model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3", "P_bg225"),
            **conv("model.diffusion_model.output_blocks.6.1.proj_out", "P_bg225", "P_bg226"),

            
            **easyblock("model.diffusion_model.output_blocks.7.0", "P_bg227", "P_bg228"),
            **conv("model.diffusion_model.output_blocks.7.0.skip_connection","P_bg229","P_bg230"),
            **norm("model.diffusion_model.output_blocks.7.1.norm", "P_bg231"),
            **conv("model.diffusion_model.output_blocks.7.1.proj_in", "P_bg231", "P_bg232"),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_q", "P_bg233", "P_bg234", bias=False),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_k", "P_bg233", "P_bg234", bias=False),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_v", "P_bg233", "P_bg234", bias=False),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0", "P_bg233","P_bg234", bias=True),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj", "P_bg235","P_bg236", bias=True),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2", "P_bg237","P_bg238", bias=True),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_q", "P_bg239", "P_bg240", bias=False),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_k", "P_bg241", "P_bg242", bias=False),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_v", "P_bg241", "P_bg242", bias=False),
            **dense("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0", "P_bg243","P_bg244", bias=True),
            **norm("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1", "P_bg244"),
            **norm("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2", "P_bg244"),
            **norm("model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3", "P_bg244"),
            **conv("model.diffusion_model.output_blocks.7.1.proj_out", "P_bg244", "P_bg245"),

            **easyblock("model.diffusion_model.output_blocks.8.0", "P_bg246","P_bg247"),
            **conv("model.diffusion_model.output_blocks.8.0.skip_connection","P_bg248","P_bg249"),
            **norm("model.diffusion_model.output_blocks.8.1.norm", "P_bg250"),
            **conv("model.diffusion_model.output_blocks.8.1.proj_in", "P_bg250", "P_bg251"),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_q", "P_bg252", "P_bg253", bias=False),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_k", "P_bg252", "P_bg253", bias=False),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_v", "P_bg252", "P_bg253", bias=False),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0", "P_bg252","P_bg253", bias=True),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj", "P_bg254","P_bg255", bias=True),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2", "P_bg256","P_bg257", bias=True),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_q", "P_bg258", "P_bg259", bias=False),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_k", "P_bg260", "P_bg261", bias=False),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_v", "P_bg260", "P_bg261", bias=False),
            **dense("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0", "P_bg262","P_bg263", bias=True),
            **norm("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1", "P_bg263"),
            **norm("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2", "P_bg263"),
            **norm("model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3", "P_bg263"),
            **conv("model.diffusion_model.output_blocks.8.1.proj_out", "P_bg263", "P_bg264"),     
            **conv("model.diffusion_model.output_blocks.8.2.conv", "P_bg265", "P_bg266"),
            
            **easyblock("model.diffusion_model.output_blocks.9.0", "P_bg267","P_bg268"),
            **conv("model.diffusion_model.output_blocks.9.0.skip_connection","P_bg269","P_bg270"), 
            **norm("model.diffusion_model.output_blocks.9.1.norm", "P_bg271"),
            **conv("model.diffusion_model.output_blocks.9.1.proj_in", "P_bg271", "P_bg272"),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_q", "P_bg273", "P_bg274", bias=False),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_k", "P_bg273", "P_bg274", bias=False),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_v", "P_bg273", "P_bg274", bias=False),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0", "P_bg273","P_bg274", bias=True),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj", "P_bg275","P_bg276", bias=True),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2", "P_bg277","P_bg278", bias=True),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_q", "P_bg279", "P_bg280", bias=False),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_k", "P_bg281", "P_bg282", bias=False),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_v", "P_bg281", "P_bg282", bias=False),
            **dense("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0", "P_bg283","P_bg284", bias=True),
            **norm("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1", "P_bg284"),
            **norm("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2", "P_bg284"),
            **norm("model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3", "P_bg284"),
            **conv("model.diffusion_model.output_blocks.9.1.proj_out", "P_bg284", "P_bg285"),     

            **easyblock("model.diffusion_model.output_blocks.10.0", "P_bg286", "P_bg287"),
            **conv("model.diffusion_model.output_blocks.10.0.skip_connection","P_bg288","P_bg289"), 
            **norm("model.diffusion_model.output_blocks.10.1.norm", "P_bg290"),
            **conv("model.diffusion_model.output_blocks.10.1.proj_in", "P_bg290", "P_bg291"),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_q", "P_bg292", "P_bg293", bias=False),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_k", "P_bg292", "P_bg293", bias=False),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_v", "P_bg292", "P_bg293", bias=False),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0", "P_bg292","P_bg293", bias=True),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj", "P_bg294","P_bg295", bias=True),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2", "P_bg296","P_bg297", bias=True),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_q", "P_bg298", "P_bg299", bias=False),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_k", "P_bg300", "P_bg301", bias=False),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_v", "P_bg300", "P_bg301", bias=False),
            **dense("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0", "P_bg302","P_bg303", bias=True),
            **norm("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1", "P_bg303"),
            **norm("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2", "P_bg303"),
            **norm("model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3", "P_bg303"),
            **conv("model.diffusion_model.output_blocks.10.1.proj_out", "P_bg303", "P_bg304"),     

            **easyblock("model.diffusion_model.output_blocks.11.0", "P_bg305", "P_bg306"),
            **conv("model.diffusion_model.output_blocks.11.0.skip_connection","P_bg307","P_bg308"), 
            **norm("model.diffusion_model.output_blocks.11.1.norm", "P_bg309"),
            **conv("model.diffusion_model.output_blocks.11.1.proj_in", "P_bg309", "P_bg310"),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_q", "P_bg311", "P_bg312", bias=False),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_k", "P_bg311", "P_bg312", bias=False),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_v", "P_bg311", "P_bg312", bias=False),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0", "P_bg311","P_bg312", bias=True),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj", "P_bg313","P_bg314", bias=True),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2", "P_bg315","P_bg316", bias=True),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_q", "P_bg317", "P_bg318", bias=False),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k", "P_bg319", "P_bg320", bias=False),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v", "P_bg319", "P_bg320", bias=False),
            **dense("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0", "P_bg321","P_bg322", bias=True),
            **norm("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1", "P_bg322"),
            **norm("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2", "P_bg322"),
            **norm("model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3", "P_bg322"),
            **conv("model.diffusion_model.output_blocks.11.1.proj_out", "P_bg322", "P_bg323"),     

            **norm("model.diffusion_model.out.0", "P_bg324"),
            **conv("model.diffusion_model.out.2", "P_bg325", "P_bg326"),
            #VAE              
            #encoder down
            **conv("first_stage_model.encoder.conv_in", "P_bg2327", "P_bg2328"),  
            **easyblock2("first_stage_model.encoder.down.0.block.0", "P_bg2328"),
            **easyblock2("first_stage_model.encoder.down.0.block.1", "P_bg2328"),
            **conv("first_stage_model.encoder.down.0.downsample.conv", "P_bg2328", "P_bg2329"),
            
            **shortcutblock("first_stage_model.encoder.down.1.block.0", "P_bg2330","P_bg2331"),
            **easyblock2("first_stage_model.encoder.down.1.block.1", "P_bg2331"),
            **conv("first_stage_model.encoder.down.1.downsample.conv", "P_bg2331", "P_bg2332"),
            
            **shortcutblock("first_stage_model.encoder.down.2.block.0", "P_bg2332", "P_bg2333"),
            **easyblock2("first_stage_model.encoder.down.2.block.1", "P_bg2333"),
            **conv("first_stage_model.encoder.down.2.downsample.conv", "P_bg2333", "P_bg2334"),

            **easyblock2("first_stage_model.encoder.down.3.block.0", "P_bg2334"),
            **easyblock2("first_stage_model.encoder.down.3.block.1", "P_bg2334"),

            #encoder mid-block
            **easyblock2("first_stage_model.encoder.mid.block_1", "P_bg2334"),

            **norm("first_stage_model.encoder.mid.attn_1.norm", "P_bg2334"),
            **conv("first_stage_model.encoder.mid.attn_1.q", "P_bg2334", "P_bg2335"),
            **conv("first_stage_model.encoder.mid.attn_1.k", "P_bg2334", "P_bg2335"),
            **conv("first_stage_model.encoder.mid.attn_1.v", "P_bg2334", "P_bg2335"),
            **conv("first_stage_model.encoder.mid.attn_1.proj_out", "P_bg2335", "P_bg2336"),    

            **easyblock2("first_stage_model.encoder.mid.block_2", "P_bg2336"),

            **norm("first_stage_model.encoder.norm_out", "P_bg2337"),
            **conv("first_stage_model.encoder.conv_out", "P_bg2338", "P_bg2339"),

            **conv("first_stage_model.decoder.conv_in", "P_bg2340", "P_bg2341"),
            
            #decoder mid-block
            **easyblock2("first_stage_model.decoder.mid.block_1", "P_bg2342"),
            **norm("first_stage_model.decoder.mid.attn_1.norm", "P_bg2342"),
            **conv("first_stage_model.decoder.mid.attn_1.q", "P_bg2342", "P_bg2343"),
            **conv("first_stage_model.decoder.mid.attn_1.k", "P_bg2342", "P_bg2343"),
            **conv("first_stage_model.decoder.mid.attn_1.v", "P_bg2342", "P_bg2343"),
            **conv("first_stage_model.decoder.mid.attn_1.proj_out", "P_bg2343", "P_bg2344"),

            **easyblock2("first_stage_model.decoder.mid.block_2", "P_bg2345"),
            
            #decoder up
            **shortcutblock("first_stage_model.decoder.up.0.block.0", "P_bg2346","P_bg2347"),
            **easyblock2("first_stage_model.decoder.up.0.block.1", "P_bg2348"),
            **easyblock2("first_stage_model.decoder.up.0.block.2", "P_bg2349"),

            **shortcutblock("first_stage_model.decoder.up.1.block.0", "P_bg2350","P_bg2351"),    
            **easyblock2("first_stage_model.decoder.up.1.block.1", "P_bg2352"),
            **easyblock2("first_stage_model.decoder.up.1.block.2", "P_bg2353"),
            **conv("first_stage_model.decoder.up.1.upsample.conv", "P_bg2353", "P_bg2354"),

            **easyblock2("first_stage_model.decoder.up.2.block.0", "P_bg2355"),
            **easyblock2("first_stage_model.decoder.up.2.block.1", "P_bg2355"),
            **easyblock2("first_stage_model.decoder.up.2.block.2", "P_bg2355"),
            **conv("first_stage_model.decoder.up.2.upsample.conv", "P_bg2355", "P_bg2356"),

            **easyblock2("first_stage_model.decoder.up.3.block.0", "P_bg2356"),
            **easyblock2("first_stage_model.decoder.up.3.block.1", "P_bg2356"),
            **easyblock2("first_stage_model.decoder.up.3.block.2", "P_bg2356"),
            **conv("first_stage_model.decoder.up.3.upsample.conv", "P_bg2356", "P_bg2357"),

            **norm("first_stage_model.decoder.norm_out", "P_bg2358"),
            **conv("first_stage_model.decoder.conv_out", "P_bg2359", "P_bg2360"),
            **conv("first_stage_model.quant_conv", "P_bg2361", "P_bg2362"),
            **conv("first_stage_model.post_quant_conv", "P_bg2363", "P_bg2364"),

            # Text Encoder 2
            # Should observe the original openCLIP Repo: https://github.com/openai/CLIP/blob/main/clip/model.py#L171
            # Size / sequence has its pattern! Somehow not compatable with ViT-L!
            **skip("cond_stage_model.model.transformer.text_model.embeddings.position_ids", None, None),
            **dense("cond_stage_model.model.transformer.text_model.embeddings.token_embedding", None, None),
            **dense("cond_stage_model.model.transformer.text_model.embeddings.position_embedding", "P_bg1170", "P_bg1171", bias=False),

            **dense("cond_stage_model.model.token_embedding", None, None),
            **norm("cond_stage_model.model.ln_final", "P_bg1430"),
            **skip("cond_stage_model.model.logit_scale", None, None),
            **skip("cond_stage_model.model.positional_embedding", None, None),
            **skip("cond_stage_model.model.text_projection", None, None),

            **dense2("cond_stage_model.model.transformer.resblocks.0.attn.in_proj", "P_bg1276", "P_bg1277", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.0.attn.out_proj", "P_bg1274", "P_bg1275", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.0.ln_1", "P_bg1275"),
            **dense("cond_stage_model.model.transformer.resblocks.0.mlp.c_fc", "P_bg1275", "P_bg1279", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.0.mlp.c_proj", "P_bg1279", "P_bg1280", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.0.ln_2", "P_bg1280"),

            **dense2("cond_stage_model.model.transformer.resblocks.1.attn.in_proj", "P_bg1282", "P_bg1283", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.1.attn.out_proj", "P_bg1280", "P_bg1281", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.1.ln_1", "P_bg1281"),
            **dense("cond_stage_model.model.transformer.resblocks.1.mlp.c_fc", "P_bg1281", "P_bg1285", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.1.mlp.c_proj", "P_bg1285", "P_bg1287", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.1.ln_2", "P_bg1287"),

            **dense2("cond_stage_model.model.transformer.resblocks.2.attn.in_proj", "P_bg1289", "P_bg1290", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.2.attn.out_proj", "P_bg1287", "P_bg1347", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.2.ln_1", "P_bg1347"),
            **dense("cond_stage_model.model.transformer.resblocks.2.mlp.c_fc", "P_bg1348", "P_bg1351", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.2.mlp.c_proj", "P_bg1351", "P_bg1353", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.2.ln_2", "P_bg1353"),

            **dense2("cond_stage_model.model.transformer.resblocks.3.attn.in_proj", "P_bg1355", "P_bg1356", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.3.attn.out_proj", "P_bg1353", "P_bg1413", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.3.ln_1", "P_bg1413"),
            **dense("cond_stage_model.model.transformer.resblocks.3.mlp.c_fc", "P_bg1413", "P_bg1417", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.3.mlp.c_proj", "P_bg1417", "P_bg1419", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.3.ln_2", "P_bg1419"),

            **dense2("cond_stage_model.model.transformer.resblocks.4.attn.in_proj", "P_bg1421", "P_bg1422", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.4.attn.out_proj", "P_bg1419", "P_bg1431", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.4.ln_1", "P_bg1431"),
            **dense("cond_stage_model.model.transformer.resblocks.4.mlp.c_fc", "P_bg1431", "P_bg1435", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.4.mlp.c_proj", "P_bg1435", "P_bg1436", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.4.ln_2", "P_bg1436"),

            **dense2("cond_stage_model.model.transformer.resblocks.5.attn.in_proj", "P_bg1438", "P_bg1439", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.5.attn.out_proj", "P_bg1436", "P_bg1437", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.5.ln_1", "P_bg1437"),
            **dense("cond_stage_model.model.transformer.resblocks.5.mlp.c_fc", "P_bg1437", "P_bg1441", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.5.mlp.c_proj", "P_bg1441", "P_bg1442", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.5.ln_2", "P_bg1442"),

            **dense2("cond_stage_model.model.transformer.resblocks.6.attn.in_proj", "P_bg1444", "P_bg1445", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.6.attn.out_proj", "P_bg1442", "P_bg1443", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.6.ln_1", "P_bg1443"),
            **dense("cond_stage_model.model.transformer.resblocks.6.mlp.c_fc", "P_bg1443", "P_bg1447", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.6.mlp.c_proj", "P_bg1447", "P_bg1448", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.6.ln_2", "P_bg1448"),

            **dense2("cond_stage_model.model.transformer.resblocks.7.attn.in_proj", "P_bg1450", "P_bg1451", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.7.attn.out_proj", "P_bg1448", "P_bg1449", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.7.ln_1", "P_bg1449"),
            **dense("cond_stage_model.model.transformer.resblocks.7.mlp.c_fc", "P_bg1449", "P_bg1453", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.7.mlp.c_proj", "P_bg1453", "P_bg1454", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.7.ln_2", "P_bg1454"),

            **dense2("cond_stage_model.model.transformer.resblocks.8.attn.in_proj", "P_bg1456", "P_bg1457", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.8.attn.out_proj", "P_bg1454", "P_bg1455", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.8.ln_1", "P_bg1455"),
            **dense("cond_stage_model.model.transformer.resblocks.8.mlp.c_fc", "P_bg1455", "P_bg1459", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.8.mlp.c_proj", "P_bg1459", "P_bg1460", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.8.ln_2", "P_bg1460"),

            **dense2("cond_stage_model.model.transformer.resblocks.9.attn.in_proj", "P_bg1462", "P_bg1463", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.9.attn.out_proj", "P_bg1460", "P_bg1461", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.9.ln_1", "P_bg1461"),
            **dense("cond_stage_model.model.transformer.resblocks.9.mlp.c_fc", "P_bg1461", "P_bg1465", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.9.mlp.c_proj", "P_bg1465", "P_bg1286", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.9.ln_2", "P_bg1286"),

            **dense2("cond_stage_model.model.transformer.resblocks.10.attn.in_proj", "P_bg1288", "P_bg1466", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.10.attn.out_proj", "P_bg1286", "P_bg1287", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.10.ln_1", "P_bg1287"),
            **dense("cond_stage_model.model.transformer.resblocks.10.mlp.c_fc", "P_bg1287", "P_bg1291", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.10.mlp.c_proj", "P_bg1291", "P_bg1292", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.10.ln_2", "P_bg1292"),

            **dense2("cond_stage_model.model.transformer.resblocks.11.attn.in_proj", "P_bg1294", "P_bg1295", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.11.attn.out_proj", "P_bg1292", "P_bg1293", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.11.ln_1", "P_bg1293"),
            **dense("cond_stage_model.model.transformer.resblocks.11.mlp.c_fc", "P_bg1293", "P_bg1297", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.11.mlp.c_proj", "P_bg1297", "P_bg1298", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.11.ln_2", "P_bg1298"),

            **dense2("cond_stage_model.model.transformer.resblocks.12.attn.in_proj", "P_bg1300", "P_bg1301", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.12.attn.out_proj", "P_bg1298", "P_bg1299", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.12.ln_1", "P_bg1299"),
            **dense("cond_stage_model.model.transformer.resblocks.12.mlp.c_fc", "P_bg1299", "P_bg1303", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.12.mlp.c_proj", "P_bg1303", "P_bg1304", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.12.ln_2", "P_bg1304"),

            **dense2("cond_stage_model.model.transformer.resblocks.13.attn.in_proj", "P_bg1306", "P_bg1307", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.13.attn.out_proj", "P_bg1304", "P_bg1305", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.13.ln_1", "P_bg1305"),
            **dense("cond_stage_model.model.transformer.resblocks.13.mlp.c_fc", "P_bg1305", "P_bg1309", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.13.mlp.c_proj", "P_bg1309", "P_bg1310", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.13.ln_2", "P_bg1310"),

            **dense2("cond_stage_model.model.transformer.resblocks.14.attn.in_proj", "P_bg1312", "P_bg1313", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.14.attn.out_proj", "P_bg1310", "P_bg1311", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.14.ln_1", "P_bg1311"),
            **dense("cond_stage_model.model.transformer.resblocks.14.mlp.c_fc", "P_bg1311", "P_bg1315", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.14.mlp.c_proj", "P_bg1315", "P_bg1316", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.14.ln_2", "P_bg1316"),

            **dense2("cond_stage_model.model.transformer.resblocks.15.attn.in_proj", "P_bg1318", "P_bg1319", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.15.attn.out_proj", "P_bg1316", "P_bg1317", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.15.ln_1", "P_bg1317"),
            **dense("cond_stage_model.model.transformer.resblocks.15.mlp.c_fc", "P_bg1317", "P_bg1321", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.15.mlp.c_proj", "P_bg1321", "P_bg1322", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.15.ln_2", "P_bg1322"),

            **dense2("cond_stage_model.model.transformer.resblocks.16.attn.in_proj", "P_bg1324", "P_bg1325", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.16.attn.out_proj", "P_bg1322", "P_bg1323", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.16.ln_1", "P_bg1323"),
            **dense("cond_stage_model.model.transformer.resblocks.16.mlp.c_fc", "P_bg1323", "P_bg1327", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.16.mlp.c_proj", "P_bg1327", "P_bg1328", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.16.ln_2", "P_bg1328"),

            **dense2("cond_stage_model.model.transformer.resblocks.17.attn.in_proj", "P_bg1330", "P_bg1331", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.17.attn.out_proj", "P_bg1328", "P_bg1329", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.17.ln_1", "P_bg1329"),
            **dense("cond_stage_model.model.transformer.resblocks.17.mlp.c_fc", "P_bg1329", "P_bg1333", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.17.mlp.c_proj", "P_bg1333", "P_bg1334", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.17.ln_2", "P_bg1334"),

            **dense2("cond_stage_model.model.transformer.resblocks.18.attn.in_proj", "P_bg1336", "P_bg1337", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.18.attn.out_proj", "P_bg1334", "P_bg1335", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.18.ln_1", "P_bg1335"),
            **dense("cond_stage_model.model.transformer.resblocks.18.mlp.c_fc", "P_bg1335", "P_bg1339", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.18.mlp.c_proj", "P_bg1339", "P_bg1340", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.18.ln_2", "P_bg1340"),

            **dense2("cond_stage_model.model.transformer.resblocks.19.attn.in_proj", "P_bg1342", "P_bg1343", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.19.attn.out_proj", "P_bg1340", "P_bg1341", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.19.ln_1", "P_bg1341"),
            **dense("cond_stage_model.model.transformer.resblocks.19.mlp.c_fc", "P_bg1341", "P_bg1345", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.19.mlp.c_proj", "P_bg1345", "P_bg1352", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.19.ln_2", "P_bg1352"),

            **dense2("cond_stage_model.model.transformer.resblocks.20.attn.in_proj", "P_bg1354", "P_bg1346", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.20.attn.out_proj", "P_bg1352", "P_bg1353", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.20.ln_1", "P_bg1353"),
            **dense("cond_stage_model.model.transformer.resblocks.20.mlp.c_fc", "P_bg1353", "P_bg1357", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.20.mlp.c_proj", "P_bg1357", "P_bg1358", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.20.ln_2", "P_bg1358"),

            **dense2("cond_stage_model.model.transformer.resblocks.21.attn.in_proj", "P_bg1360", "P_bg1361", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.21.attn.out_proj", "P_bg1358", "P_bg1359", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.21.ln_1", "P_bg1359"),
            **dense("cond_stage_model.model.transformer.resblocks.21.mlp.c_fc", "P_bg1359", "P_bg1363", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.21.mlp.c_proj", "P_bg1363", "P_bg1364", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.21.ln_2", "P_bg1364"),

            **dense2("cond_stage_model.model.transformer.resblocks.22.attn.in_proj", "P_bg1366", "P_bg1367", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.22.attn.out_proj", "P_bg1364", "P_bg1365", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.22.ln_1", "P_bg1365"),
            **dense("cond_stage_model.model.transformer.resblocks.22.mlp.c_fc", "P_bg1365", "P_bg1369", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.22.mlp.c_proj", "P_bg1369", "P_bg1370", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.22.ln_2", "P_bg1370"),

            **dense2("cond_stage_model.model.transformer.resblocks.23.attn.in_proj", "P_bg1372", "P_bg1373", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.23.attn.out_proj", "P_bg1370", "P_bg1371", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.23.ln_1", "P_bg1371"),
            **dense("cond_stage_model.model.transformer.resblocks.23.mlp.c_fc", "P_bg1371", "P_bg1375", bias=True),
            **dense("cond_stage_model.model.transformer.resblocks.23.mlp.c_proj", "P_bg1375", "P_bg1376", bias=True),
            **norm("cond_stage_model.model.transformer.resblocks.23.ln_2", "P_bg1376"),

        }
    )